### ISSUE TITLE
Make password_changed.html match rest of styling

### ISSUE THREAD

**Issue by aaronred345** [aaronred345/tyronehub#1]
The password changed page is still from a test design, having it match the rest of the styling would be really nice.

**Comment by OpenCalligraphy** [comment]
Could you assign the issue to me? I would be interested in contributing here :)

**Comment by aaronred345** [comment]
Absolutely, thank you for your help :) <3

**Comment by aaronred345** [comment]
Oh I see, for whatever reason in a few apps the migrations folder wasn't made automatically. It contains the __init__.py which lets django know it's a python package to import. I've gone ahead and pushed them to the repo. That SHOULD fix it. (I did a fresh download of the repo to test from a clean slate)

I've also added in the default settings.ini file

**Comment by aaronred345** [comment]
All you should need to do is migrate, if it's still not working, try running the `py manage.py makemigration <appname>` and `py manage.py migrate <appname>` for each app as that's what I initially did to fix this

**Comment by aaronred345** [comment]
Wonderful! I'm glad thig to sorted out before deployment and release lmao.
